version: '2'

services:

  customer:
    build:
      context: ./customer
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    networks:
      - corebank-network

  account:
    build:
      context: ./account
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    networks:
      - corebank-network


  deposit-withdrawal:
    build:
      context: ./deposit-withdrawal
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    networks:
      - corebank-network

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mysql-customer:
    image: mysql:latest
    container_name: mysql-customer
    ports:
      - "3320:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: customer
    volumes:
      - /var/lib/docker/volumes/mysql-customer:/var/lib/mysql

  mysql-account:
    image: mysql:latest
    container_name: mysql-account
    ports:
      - "3321:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: account
    volumes:
      - /var/lib/docker/volumes/mysql-account:/var/lib/mysql

  mysql-deposit-withdrawal:
    image: mysql:latest
    container_name: mysql-deposit-withdrawal
    ports:
      - "3322:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: deposit-withdrawal
    volumes:
      - /var/lib/docker/volumes/mysql-deposit-withdrawal:/var/lib/mysql

networks:
  corebank-network:
    driver: bridge