server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: orchestrator
            uri: http://localhost:8081/
            predicates:
              - Path=/*